# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=2, max_digits=9999)),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=9999)),
                ('nombrecell', models.CharField(max_length=100)),
                ('ipv4', models.DecimalField(decimal_places=2, max_digits=9999)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
